# Data input

In [5]:
import pandas as pd
import numpy as np
import bq_helper
from bq_helper import BigQueryHelper
# https://www.kaggle.com/sohier/introduction-to-the-bq-helper-package
genomes = bq_helper.BigQueryHelper(active_project="bigquery-public-data",
                                   dataset_name="genomics_cannabis")

In [6]:
bq_assistant = BigQueryHelper("bigquery-public-data", "genomics_cannabis")
bq_assistant.list_tables()

['MNPR01_201703',
 'MNPR01_reference_201703',
 'MNPR01_transcriptome_201703',
 'cs10_gff',
 'cs3k_project_info',
 'cs3k_vcf_cs10_dv090',
 'sample_info_201703']

In [7]:
bq_assistant.table_schema("cs3k_project_info")

                  name     type      mode description
0           AvgSpotLen  INTEGER  NULLABLE
1            BioSample   STRING  NULLABLE
2   DATASTORE_provider   STRING  NULLABLE
3     DATASTORE_region   STRING  NULLABLE
4           Experiment   STRING  NULLABLE
5           InsertSize  INTEGER  NULLABLE
6        LibraryLayout   STRING  NULLABLE
7         Library_Name   STRING  NULLABLE
8               MBases  INTEGER  NULLABLE
9               MBytes  INTEGER  NULLABLE
10                 Run   STRING  NULLABLE
11          SRA_Sample   STRING  NULLABLE
12         Sample_Name   STRING  NULLABLE
13          Assay_Type   STRING  NULLABLE
14          BioProject   STRING  NULLABLE
15         Center_Name   STRING  NULLABLE
16             Consent   STRING  NULLABLE
17  DATASTORE_filetype   STRING  NULLABLE
18          Instrument   STRING  NULLABLE
19    LibrarySelection   STRING  NULLABLE
20       LibrarySource   STRING  NULLABLE
21            LoadDate     DATE  NULLABLE
22            Organism   STRING  NULLABLE
23            Platform   STRING  NULLABLE
24         ReleaseDate     DATE  NULLABLE
25           SRA_Study   STRING  NULLABLE

In [14]:
bq_assistant.head("MNPR01_201703", num_rows=10)

,reference_name,start,end,reference_bases,alternate_bases,variant_id,quality,filter,names,call,...,RPPR,RPR,RUN,SAF,SAP,SAR,SRF,SRP,SRR,TYPE
0,gi|1098496801|gb|MNPR01000114.1|,318648,318654,TCAAAG,[TCGAAG],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTY4MDF8Z2J8TU5QUj...,24.77870,[],[],"[{'call_set_id': '17527604790083478309-1647', ...",...,0.0,[0],[1],[0],[5.18177],[1],0,0.0,0,[snp]
1,gi|1098489786|gb|MNPR01004871.1|,11908,11914,CCTTGC,[TTTTGC],CKXG8eKP9qOf8wESIGdpfDEwOTg0ODk3ODZ8Z2J8TU5QUj...,17.87680,[],[],"[{'call_set_id': '17527604790083478309-1532', ...",...,0.0,[0],[1],[1],[5.18177],[0],0,0.0,0,[mnp]
2,gi|1098496792|gb|MNPR01000118.1|,348937,348947,CTCAACTTGC,[TTCAATTTGT],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTY3OTJ8Z2J8TU5QUj...,29.52050,[],[],"[{'call_set_id': '17527604790083478309-1532', ...",...,0.0,[0],[1],[1],[5.18177],[0],0,0.0,0,[complex]
3,gi|1098495754|gb|MNPR01000694.1|,72508,72512,GTAG,[ATAG],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTU3NTR8Z2J8TU5QUj...,3.77924,[],[],"[{'call_set_id': '17527604790083478309-1532', ...",...,0.0,[1],[1],[0],[5.18177],[1],0,0.0,0,[snp]
4,gi|1098489564|gb|MNPR01005041.1|,8695,8699,TCAA,[TAAA],CKXG8eKP9qOf8wESIGdpfDEwOTg0ODk1NjR8Z2J8TU5QUj...,24.89040,[],[],"[{'call_set_id': '17527604790083478309-1532', ...",...,0.0,[0],[1],[0],[5.18177],[1],0,0.0,0,[snp]
5,gi|1098493040|gb|MNPR01002808.1|,10232,10238,GGATTG,[GAATTA],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTMwNDB8Z2J8TU5QUj...,21.51740,[],[],"[{'call_set_id': '17527604790083478309-1532', ...",...,0.0,[1],[1],[0],[5.18177],[1],0,0.0,0,[complex]
6,gi|1098494910|gb|MNPR01001505.1|,6201,6211,TAAAAAAAAT,[TAAAAAAT],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTQ5MTB8Z2J8TU5QUj...,28.77160,[],[],"[{'call_set_id': '17527604790083478309-1035', ...",...,0.0,[0],[1],[0],[5.18177],[1],0,0.0,0,[del]
7,gi|1098496059|gb|MNPR01000497.1|,63172,63177,GGAAG,[GAAAA],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTYwNTl8Z2J8TU5QUj...,13.94160,[],[],"[{'call_set_id': '17527604790083478309-1532', ...",...,0.0,[0],[1],[0],[5.18177],[1],0,0.0,0,[complex]
8,gi|1098497076|gb|MNPR01000034.1|,389457,389462,GGGGT,[TGGCT],CKXG8eKP9qOf8wESIGdpfDEwOTg0OTcwNzZ8Z2J8TU5QUj...,10.72590,[],[],"[{'call_set_id': '17527604790083478309-1035', ...",...,0.0,[0],[1],[0],[5.18177],[1],0,0.0,0,[complex]
9,gi|1098484780|gb|MNPR01007372.1|,8354,8356,GT,[GA],CKXG8eKP9qOf8wESIGdpfDEwOTg0ODQ3ODB8Z2J8TU5QUj...,13.93370,[],[],"[{'call_set_id': '17527604790083478309-1647', ...",...,0.0,[1],[1],[1],[5.18177],[0],0,0.0,0,[snp]